# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_goals', models.IntegerField()),
                ('player_two_goals', models.IntegerField()),
                ('result', models.CharField(max_length=200)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('logo_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=200)),
                ('tournament_type', models.CharField(max_length=200)),
                ('number_of_games', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('total_goals', models.IntegerField()),
                ('points', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='gamesummary',
            name='player_one_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_team', to='league.Team'),
        ),
        migrations.AddField(
            model_name='gamesummary',
            name='player_two_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two_team', to='league.Team'),
        ),
        migrations.AddField(
            model_name='gamesummary',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Tournament'),
        ),
    ]
