# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0004_auto_20170402_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesummary',
            name='player_two',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
