# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0005_gamesummary_player_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_record', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_two_record', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Tournament')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tournamentgamerecord',
            unique_together=set([('tournament', 'player_one', 'player_two')]),
        ),
    ]
