# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_auto_20170424_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentsummary',
            old_name='away_goals',
            new_name='goals',
        ),
        migrations.RemoveField(
            model_name='tournamentsummary',
            name='home_goals',
        ),
    ]
