# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20170424_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesummary',
            name='player_one_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_one_team', to='league.Team'),
        ),
        migrations.AlterField(
            model_name='gamesummary',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesummary',
            name='player_two_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two_team', to='league.Team'),
        ),
    ]
